# ***Import and Misecellaneous***

In [ ]:
import pandas as pd
import numpy as np
import sklearn
import seaborn as sns
from sklearn.cluster import Birch
from numpy import unique
from numpy import where
from matplotlib import pyplot
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
data =  pd.read_csv("/content/drive/MyDrive/University of Windsor/cleaned and perfected.csv")
data = data.drop(['Unnamed: 0'], axis = 'columns')
data.iloc[list(data[data['7'] > 1.0]['7'].index),5]  = 0

# ***Analysis and Modelling***

In [ ]:
X = data.drop('response', axis=1)
y = data['response']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

# ***Linear Sigmoid Gaussian***

linear

In [ ]:
svclassifier = SVC(kernel='poly')
svclassifier.fit(X_train, y_train)
y_pred = svclassifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[663   7]
 [ 49 263]]
              precision    recall  f1-score   support

           0       0.93      0.99      0.96       670
           1       0.97      0.84      0.90       312

    accuracy                           0.94       982
   macro avg       0.95      0.92      0.93       982
weighted avg       0.94      0.94      0.94       982



sigmoid

In [ ]:
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)
y_pred = svclassifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[670   0]
 [312   0]]
              precision    recall  f1-score   support

           0       0.68      1.00      0.81       670
           1       0.00      0.00      0.00       312

    accuracy                           0.68       982
   macro avg       0.34      0.50      0.41       982
weighted avg       0.47      0.68      0.55       982



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Gaussian

In [ ]:
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)
y_pred = svclassifier.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[666   4]
 [ 77 235]]
              precision    recall  f1-score   support

           0       0.90      0.99      0.94       670
           1       0.98      0.75      0.85       312

    accuracy                           0.92       982
   macro avg       0.94      0.87      0.90       982
weighted avg       0.92      0.92      0.91       982

